"""Intrinsic max-normalized enstrophy localization generated by Navier--Stokes.

The module deliberately avoids a finite external badness threshold.  For a smooth
periodic Navier--Stokes state let

    e = |omega|^2/2,       M(t) = max_x e(x,t),       g = e/M.

The whole nested family Omega_theta={g>=theta}, 0<theta<1, is then generated by the
physical state itself.  At a regular boundary e=theta M the exact enstrophy PDE gives

    V_n - u.n_out = [R - theta Mdot]/|grad e|,
    R = omega.S.omega - nu|grad omega|^2 + nu Delta e.

Thus the Eulerian/material slip of the localization boundary is a compatibility face
built from the same stretching, Kelvin-bulk, and curvature laws that govern local
enstrophy.  No selector force or selector Brownian source is introduced.

The normalized defect (R-theta Mdot)/M^(3/2) and normalized gradient
|grad e|/M^(5/4) are invariant under the Navier--Stokes similarity scaling.  This is
necessary physical typing only: the max-normalized filtration is an intrinsic
candidate localization, not a proved first-bad/continuation criterion.
"""
from __future__ import annotations

from collections.abc import Sequence
import sympy as sp

from .first_bad_candidate_exclusions import gradient, laplacian
from .local_enstrophy_kelvin_growth_gate import enstrophy_balance_faces, enstrophy_density

Matrix = sp.MatrixBase


def navier_stokes_similarity_weights() -> dict[str, int]:
    """Scaling exponents under u_lam(x,t)=lam u(lam x,lam^2 t)."""
    return {
        "length": -1,
        "time": -2,
        "velocity": 1,
        "vorticity": 2,
        "enstrophy": 4,
        "grad_enstrophy": 5,
        "enstrophy_rate": 6,
        "stretching": 6,
        "kelvin_bulk": 6,
        "curvature_diffusion": 6,
        "boundary_speed": 1,
    }


def normalized_enstrophy(enstrophy: sp.Expr, max_enstrophy: sp.Expr) -> sp.Expr:
    """g=e/M.  M must be positive on the state being localized."""
    return sp.simplify(enstrophy / max_enstrophy)


def local_enstrophy_growth_rate(
    stretching: sp.Expr,
    kelvin_bulk: sp.Expr,
    curvature_diffusion: sp.Expr,
) -> sp.Expr:
    """R=stretching-Kelvin_bulk+curvature; equals e_t+u.grad e on NS states."""
    return sp.simplify(stretching - kelvin_bulk + curvature_diffusion)


def max_envelope_right_dini(active_rates: Sequence[sp.Expr]) -> sp.Expr:
    """Right Dini derivative of a finite smooth max envelope at an active tie."""
    if not active_rates:
        raise ValueError("active rate set cannot be empty")
    return sp.Max(*active_rates)


def max_envelope_left_dini(active_rates: Sequence[sp.Expr]) -> sp.Expr:
    """Left Dini derivative of a finite smooth max envelope at an active tie."""
    if not active_rates:
        raise ValueError("active rate set cannot be empty")
    return sp.Min(*active_rates)


def superlevel_material_compatibility_defect(
    local_growth_rate: sp.Expr,
    theta: sp.Expr,
    max_rate: sp.Expr,
) -> sp.Expr:
    """C_theta=R-theta Mdot on the regular boundary e=theta M."""
    return sp.simplify(local_growth_rate - theta * max_rate)


def max_normalized_superlevel_relative_speed(
    local_growth_rate: sp.Expr,
    theta: sp.Expr,
    max_rate: sp.Expr,
    grad_enstrophy_norm: sp.Expr,
) -> sp.Expr:
    """Exact outward normal speed relative to fluid u on e=theta M.

    For Omega_theta={e>=theta M}, n_out=-grad(e)/|grad(e)|.  The level-set law gives
    V_n-u.n_out=(R-theta Mdot)/|grad e|.
    """
    return sp.simplify(
        superlevel_material_compatibility_defect(local_growth_rate, theta, max_rate)
        / grad_enstrophy_norm
    )


def normalized_superlevel_compatibility_defect(
    local_growth_rate: sp.Expr,
    theta: sp.Expr,
    max_rate: sp.Expr,
    max_enstrophy: sp.Expr,
) -> sp.Expr:
    """Similarity-invariant defect C_theta/M^(3/2)."""
    return sp.simplify(
        superlevel_material_compatibility_defect(local_growth_rate, theta, max_rate)
        / max_enstrophy ** sp.Rational(3, 2)
    )


def normalized_enstrophy_gradient(
    grad_enstrophy_norm: sp.Expr,
    max_enstrophy: sp.Expr,
) -> sp.Expr:
    """Similarity-invariant regular-level gradient |grad e|/M^(5/4)."""
    return sp.simplify(grad_enstrophy_norm / max_enstrophy ** sp.Rational(5, 4))


def normalized_relative_speed_residual(
    relative_speed: sp.Expr,
    compatibility_defect_normalized: sp.Expr,
    gradient_normalized: sp.Expr,
    max_enstrophy: sp.Expr,
) -> sp.Expr:
    """Residual of (V_n-u.n)/M^(1/4)=C_hat/G_hat."""
    return sp.simplify(
        relative_speed / max_enstrophy ** sp.Rational(1, 4)
        - compatibility_defect_normalized / gradient_normalized
    )


def ancestry_boundary_mass_flux_density(
    density: sp.Expr,
    boundary_normal_speed: sp.Expr,
    ancestry_current_normal_speed: sp.Expr,
) -> sp.Expr:
    """Signed mass flux into a moving chamber for continuity current J=q c."""
    return sp.simplify(density * (boundary_normal_speed - ancestry_current_normal_speed))


def ancestry_superlevel_flux_faces(
    density: sp.Expr,
    fluid_normal_speed: sp.Expr,
    ancestry_current_normal_speed: sp.Expr,
    compatibility_defect: sp.Expr,
    grad_enstrophy_norm: sp.Expr,
) -> dict[str, sp.Expr]:
    """Exact split of moving-readout flux into ancestry/material mismatch + level slip."""
    material_ancestry = sp.simplify(
        density * (fluid_normal_speed - ancestry_current_normal_speed)
    )
    level_slip = sp.simplify(density * compatibility_defect / grad_enstrophy_norm)
    total = sp.simplify(material_ancestry + level_slip)
    direct = ancestry_boundary_mass_flux_density(
        density,
        fluid_normal_speed + compatibility_defect / grad_enstrophy_norm,
        ancestry_current_normal_speed,
    )
    return {
        "material_ancestry_mismatch": material_ancestry,
        "intrinsic_level_slip": level_slip,
        "total": total,
        "direct": direct,
        "residual": sp.simplify(total - direct),
    }


def integer_scaled_one_mode_heat_shear(
    amplitude: sp.Expr,
    mode: sp.Expr,
    y: sp.Symbol,
    t: sp.Symbol,
    nu: sp.Expr,
) -> sp.Expr:
    """Exact periodic similarity family U_n=n A exp(-nu n^2 t) sin(n y)."""
    return sp.simplify(mode * amplitude * sp.exp(-nu * mode**2 * t) * sp.sin(mode * y))


def integer_scaled_one_mode_velocity(
    amplitude: sp.Expr,
    mode: sp.Expr,
    coords: tuple[sp.Symbol, sp.Symbol, sp.Symbol],
    t: sp.Symbol,
    nu: sp.Expr,
) -> Matrix:
    _, y, _ = coords
    return sp.Matrix([integer_scaled_one_mode_heat_shear(amplitude, mode, y, t, nu), 0, 0])


def integer_scaled_one_mode_vorticity(
    amplitude: sp.Expr,
    mode: sp.Expr,
    y: sp.Symbol,
    t: sp.Symbol,
    nu: sp.Expr,
) -> Matrix:
    U = integer_scaled_one_mode_heat_shear(amplitude, mode, y, t, nu)
    return sp.Matrix([0, 0, sp.simplify(-sp.diff(U, y))])


def integer_scaled_one_mode_ns_residual(
    amplitude: sp.Expr,
    mode: sp.Expr,
    coords: tuple[sp.Symbol, sp.Symbol, sp.Symbol],
    t: sp.Symbol,
    nu: sp.Expr,
) -> Matrix:
    """Momentum residual with constant pressure; advection vanishes for x-shear."""
    u = integer_scaled_one_mode_velocity(amplitude, mode, coords, t, nu)
    Gu = gradient(u, coords)
    adv = sp.simplify(Gu * u)
    return sp.simplify(sp.diff(u, t) + adv - nu * laplacian(u, coords))


def one_mode_intrinsic_localization_calibration(
    amplitude: sp.Expr,
    mode: sp.Expr,
    theta: sp.Expr,
    coords: tuple[sp.Symbol, sp.Symbol, sp.Symbol],
    t: sp.Symbol,
    nu: sp.Expr,
) -> dict[str, sp.Expr | Matrix]:
    """Exact periodic NS: raw faces grow with mode but normalized profile is stationary.

    On a regular level cos^2(n y)=theta, the local PDE rate and theta*Mdot agree
    exactly.  Kelvin bulk and curvature are separately active but their combination,
    together with the global max decay, gives zero normalized-level slip.
    """
    _, y, _ = coords
    u = integer_scaled_one_mode_velocity(amplitude, mode, coords, t, nu)
    omega = integer_scaled_one_mode_vorticity(amplitude, mode, y, t, nu)
    faces = enstrophy_balance_faces(u, omega, coords, t, nu)
    e = sp.simplify(faces["enstrophy"])
    decay = sp.exp(-2 * nu * mode**2 * t)
    M = sp.simplify(sp.Rational(1, 2) * amplitude**2 * mode**4 * decay)
    Mdot = sp.simplify(sp.diff(M, t))
    g = sp.simplify(e / M)

    # Evaluate physical faces on a regular boundary through cos^2(n y)=theta,
    # sin^2(n y)=1-theta and cos(2 n y)=2 theta-1.
    bulk_level = sp.simplify(nu * amplitude**2 * mode**6 * decay * (1 - theta))
    curvature_level = sp.simplify(
        nu * amplitude**2 * mode**6 * decay * (1 - 2 * theta)
    )
    stretching_level = sp.Integer(0)
    local_rate_level = local_enstrophy_growth_rate(
        stretching_level, bulk_level, curvature_level
    )
    defect = superlevel_material_compatibility_defect(local_rate_level, theta, Mdot)
    bulk_exact = sp.simplify(
        nu * amplitude**2 * mode**6 * decay * sp.sin(mode * y) ** 2
    )
    curvature_exact = sp.simplify(
        -nu * amplitude**2 * mode**6 * decay * sp.cos(2 * mode * y)
    )
    time_exact = sp.simplify(
        -nu * amplitude**2 * mode**6 * decay * sp.cos(mode * y) ** 2
    )
    return {
        "velocity": u,
        "vorticity": omega,
        "enstrophy": e,
        "max_enstrophy": M,
        "max_rate": Mdot,
        "normalized_enstrophy": sp.trigsimp(g),
        "normalized_time_derivative": sp.simplify(sp.diff(sp.trigsimp(g), t)),
        "stretching_level": stretching_level,
        "kelvin_bulk_level": bulk_level,
        "curvature_level": curvature_level,
        "local_growth_rate_level": local_rate_level,
        "compatibility_defect": sp.simplify(defect),
        "stretching_expression_residual": sp.simplify(faces["stretching"]),
        "kelvin_bulk_expression_residual": sp.simplify(sp.trigsimp(faces["kelvin_bulk"] - bulk_exact)),
        "curvature_expression_residual": sp.simplify(sp.trigsimp(faces["curvature_diffusion"] - curvature_exact)),
        "time_expression_residual": sp.simplify(sp.trigsimp(faces["time"] - time_exact)),
        "enstrophy_balance_residual": sp.simplify(sp.trigsimp(faces["balance_residual"])),
        "ns_residual": integer_scaled_one_mode_ns_residual(amplitude, mode, coords, t, nu),
    }


def one_mode_similarity_threshold_no_go(
    amplitude: sp.Expr,
    mode: sp.Symbol,
    theta: sp.Expr,
    nu: sp.Expr,
) -> dict[str, sp.Expr]:
    """At t=0 raw enstrophy/Kelvin-bulk scale up while intrinsic defect stays zero."""
    M0 = sp.simplify(sp.Rational(1, 2) * amplitude**2 * mode**4)
    bulk0 = sp.simplify(nu * amplitude**2 * mode**6 * (1 - theta))
    curvature0 = sp.simplify(nu * amplitude**2 * mode**6 * (1 - 2 * theta))
    Mdot0 = sp.simplify(-nu * amplitude**2 * mode**6)
    rate0 = sp.simplify(-bulk0 + curvature0)
    defect0 = sp.simplify(rate0 - theta * Mdot0)
    return {
        "max_enstrophy": M0,
        "kelvin_bulk": bulk0,
        "curvature": curvature0,
        "max_rate": Mdot0,
        "local_rate": rate0,
        "compatibility_defect": defect0,
        "max_enstrophy_n4_coefficient": sp.simplify(M0 / mode**4),
        "kelvin_bulk_n6_coefficient": sp.simplify(bulk0 / mode**6),
    }


def four_mode_global_crossing_vorticity_scalar(
    y: sp.Symbol,
    t: sp.Symbol,
    nu: sp.Expr,
) -> sp.Expr:
    """Exact heat-shear vorticity designed to exchange two true global maxima.

    At t*=1/nu its cosine coefficients are (1,4,-1,2).  The initial coefficients
    contain the compensating exp(k^2) factors so every mode solves q_t=nu q_yy.
    """
    return sp.simplify(
        sp.exp(1 - nu * t) * sp.cos(y)
        + 4 * sp.exp(4 - 4 * nu * t) * sp.cos(2 * y)
        - sp.exp(9 - 9 * nu * t) * sp.cos(3 * y)
        + 2 * sp.exp(16 - 16 * nu * t) * sp.cos(4 * y)
    )


def four_mode_global_crossing_velocity_scalar(
    y: sp.Symbol,
    t: sp.Symbol,
    nu: sp.Expr,
) -> sp.Expr:
    """U with -U_y=q for the exact four-mode crossing calibration."""
    return sp.simplify(
        -sp.exp(1 - nu * t) * sp.sin(y)
        - 2 * sp.exp(4 - 4 * nu * t) * sp.sin(2 * y)
        + sp.Rational(1, 3) * sp.exp(9 - 9 * nu * t) * sp.sin(3 * y)
        - sp.Rational(1, 2) * sp.exp(16 - 16 * nu * t) * sp.sin(4 * y)
    )


def four_mode_global_crossing_calibration(
    coords: tuple[sp.Symbol, sp.Symbol, sp.Symbol],
    t: sp.Symbol,
    nu: sp.Expr,
) -> dict[str, sp.Expr | Matrix]:
    """Exact periodic NS with a genuine two-point global-max envelope crossing.

    At t*=1/nu, writing c=cos y,

      q_*(c)=16c^4-4c^3-8c^2+4c-2,
      6-q_*=4(1-c^2)(4c^2-c+2)>=0.

    Also

      6+q_*=4[4(c^2-1/4)^2+3/4+c(1-c^2)]>0

    because |c(1-c^2)|<=2/(3 sqrt(3))<3/4 on [-1,1].  Hence |q_*|<=6,
    with equality only at c=+/-1.  Thus y=0,pi are the true global enstrophy
    maxima at the tie.  Their negative transverse Hessians and the strict interior
    gap persist locally in time, while their endpoint values exchange order.
    """
    x, y, z = coords
    U = four_mode_global_crossing_velocity_scalar(y, t, nu)
    q = four_mode_global_crossing_vorticity_scalar(y, t, nu)
    u = sp.Matrix([U, 0, 0])
    omega = sp.Matrix([0, 0, q])
    T = sp.simplify(1 / nu)
    e = sp.simplify(q**2 / 2)
    q0 = sp.simplify(q.subs({y: 0, t: T}))
    qpi = sp.simplify(q.subs({y: sp.pi, t: T}))
    e0 = sp.simplify(e.subs({y: 0, t: T}))
    epi = sp.simplify(e.subs({y: sp.pi, t: T}))
    et0 = sp.simplify(sp.diff(e, t).subs({y: 0, t: T}))
    etpi = sp.simplify(sp.diff(e, t).subs({y: sp.pi, t: T}))
    eyy0 = sp.simplify(sp.diff(e, y, 2).subs({y: 0, t: T}))
    eyy_pi = sp.simplify(sp.diff(e, y, 2).subs({y: sp.pi, t: T}))
    q0_t = sp.simplify(sp.diff(q, t).subs({y: 0, t: T}))
    qpi_t = sp.simplify(sp.diff(q, t).subs({y: sp.pi, t: T}))
    gap = sp.simplify(e.subs(y, 0) - e.subs(y, sp.pi))
    gap_rate = sp.simplify(sp.diff(gap, t).subs(t, T))

    c = sp.symbols("c_global_crossing", real=True)
    qpoly = sp.expand(16 * c**4 - 4 * c**3 - 8 * c**2 + 4 * c - 2)
    upper_certificate = sp.factor(6 - qpoly)
    lower_square_part = sp.expand(4 * (c**2 - sp.Rational(1, 4)) ** 2 + sp.Rational(3, 4))
    lower_remainder = sp.expand(c * (1 - c**2))
    lower_margin = sp.simplify(sp.Rational(3, 4) - 2 / (3 * sp.sqrt(3)))
    lower_decomposition_residual = sp.expand(
        6 + qpoly - 4 * (lower_square_part + lower_remainder)
    )
    h = sp.simplify(c * (1 - c**2))
    hcrit_plus = sp.simplify(h.subs(c, 1 / sp.sqrt(3)))
    hcrit_minus = sp.simplify(h.subs(c, -1 / sp.sqrt(3)))

    faces = enstrophy_balance_faces(u, omega, coords, t, nu)
    p0 = {y: 0, t: T}
    ppi = {y: sp.pi, t: T}
    return {
        "velocity": u,
        "vorticity": omega,
        "crossing_time": T,
        "q0": q0,
        "qpi": qpi,
        "common_max_enstrophy": e0,
        "common_max_residual": sp.simplify(e0 - epi),
        "rate_0": et0,
        "rate_pi": etpi,
        "q_rate_0": q0_t,
        "q_rate_pi": qpi_t,
        "gap_rate": gap_rate,
        "left_dini": etpi,
        "right_dini": et0,
        "dini_jump": sp.simplify(et0 - etpi),
        "hessian_yy_0": eyy0,
        "hessian_yy_pi": eyy_pi,
        "qstar_polynomial": qpoly,
        "upper_global_certificate": upper_certificate,
        "upper_certificate_residual": sp.expand(
            upper_certificate - 4 * (1 - c**2) * (4 * c**2 - c + 2)
        ),
        "lower_square_part": lower_square_part,
        "lower_remainder": lower_remainder,
        "lower_decomposition_residual": lower_decomposition_residual,
        "lower_remainder_critical_plus": hcrit_plus,
        "lower_remainder_critical_minus": hcrit_minus,
        "lower_margin": lower_margin,
        "stretching_0": sp.simplify(faces["stretching"].subs(p0)),
        "stretching_pi": sp.simplify(faces["stretching"].subs(ppi)),
        "kelvin_bulk_0": sp.simplify(faces["kelvin_bulk"].subs(p0)),
        "kelvin_bulk_pi": sp.simplify(faces["kelvin_bulk"].subs(ppi)),
        "curvature_0": sp.simplify(faces["curvature_diffusion"].subs(p0)),
        "curvature_pi": sp.simplify(faces["curvature_diffusion"].subs(ppi)),
        "balance_0": sp.simplify(
            et0 - local_enstrophy_growth_rate(
                faces["stretching"].subs(p0),
                faces["kelvin_bulk"].subs(p0),
                faces["curvature_diffusion"].subs(p0),
            )
        ),
        "balance_pi": sp.simplify(
            etpi - local_enstrophy_growth_rate(
                faces["stretching"].subs(ppi),
                faces["kelvin_bulk"].subs(ppi),
                faces["curvature_diffusion"].subs(ppi),
            )
        ),
        "ns_residual": sp.simplify(
            sp.diff(u, t) + gradient(u, coords) * u - nu * laplacian(u, coords)
        ),
    }


def similarity_normalized_defect_residual(
    scale: sp.Expr,
    local_rate: sp.Expr,
    theta: sp.Expr,
    max_rate: sp.Expr,
    max_enstrophy: sp.Expr,
) -> sp.Expr:
    """Audit invariance of C_theta/M^(3/2) under exact NS similarity weights."""
    before = normalized_superlevel_compatibility_defect(
        local_rate, theta, max_rate, max_enstrophy
    )
    after = normalized_superlevel_compatibility_defect(
        scale**6 * local_rate,
        theta,
        scale**6 * max_rate,
        scale**4 * max_enstrophy,
    )
    return sp.simplify(after - before)


def similarity_normalized_speed_residual(
    scale: sp.Expr,
    relative_speed: sp.Expr,
    max_enstrophy: sp.Expr,
) -> sp.Expr:
    """Audit invariance of relative boundary speed divided by M^(1/4)."""
    before = sp.simplify(relative_speed / max_enstrophy ** sp.Rational(1, 4))
    after = sp.simplify(
        scale * relative_speed / (scale**4 * max_enstrophy) ** sp.Rational(1, 4)
    )
    return sp.simplify(after - before)
