"""Literal oriented material-surface moment hierarchy for reverse-age NS flow.

No closure ansatz is introduced.  For a material surface written in anchor-relative
coordinates r, the reverse-age relative velocity is

    v_R(r) = -[u(X+r)-u(X)].

The oriented area element a=n dA evolves by

    a_dot = (div v_R I - grad v_R^T) a = A(X+r)^T a

for incompressible Navier--Stokes, because grad v_R=-A(X+r).

Therefore every oriented monomial moment has an exact transport law.  Affine
velocity closes each moment order on itself.  A nonlinear velocity jet of degree p
couples order m to order m+p-1.  This is a physical hierarchy generated by the
velocity-difference flow, not an estimate or a chosen moment model.
"""
from __future__ import annotations

from collections.abc import Mapping, Sequence

import sympy as sp

Matrix = sp.MatrixBase
Exponent = tuple[int, ...]


def _validate_exponent(exponent: Exponent, dim: int) -> None:
    if len(exponent) != dim or any((not isinstance(q, int)) or q < 0 for q in exponent):
        raise ValueError("exponent must be a nonnegative integer tuple of spatial dimension")


def monomial(relative: Matrix, exponent: Exponent) -> sp.Expr:
    """r^alpha for a column relative-coordinate vector."""
    if relative.cols != 1:
        raise ValueError("relative coordinate must be a column vector")
    _validate_exponent(exponent, relative.rows)
    out = sp.Integer(1)
    for i, power in enumerate(exponent):
        out *= relative[i] ** power
    return sp.expand(out)


def exponent_degree(exponent: Exponent) -> int:
    return sum(exponent)


def reverse_age_oriented_moment_rate_integrand(
    relative: Matrix,
    oriented_area_element: Matrix,
    velocity_difference: Matrix,
    grad_u_at_point: Matrix,
    exponent: Exponent,
) -> Matrix:
    """Exact incompressible reverse-age rate of r^alpha (n dA).

    `velocity_difference` is u(X+r)-u(X), so rdot=-velocity_difference.
    `grad_u_at_point` is A(X+r), hence (n dA)_dot=A(X+r)^T(n dA).
    """
    if relative.cols != 1 or oriented_area_element.shape != relative.shape:
        raise ValueError("relative and oriented area element must be equal column vectors")
    n = relative.rows
    if velocity_difference.shape != (n, 1) or grad_u_at_point.shape != (n, n):
        raise ValueError("velocity/gradient dimension mismatch")
    _validate_exponent(exponent, n)
    base = monomial(relative, exponent)
    out = sp.simplify(base * grad_u_at_point.T * oriented_area_element)
    for i, power in enumerate(exponent):
        if power == 0:
            continue
        reduced = list(exponent)
        reduced[i] -= 1
        out -= power * monomial(relative, tuple(reduced)) * velocity_difference[i] * oriented_area_element
    return sp.simplify(out)


def affine_reverse_age_oriented_moment_rate(
    moments: Mapping[Exponent, Matrix],
    exponent: Exponent,
    grad_u: Matrix,
) -> Matrix:
    """Exact same-order affine closure for M_alpha=int r^alpha n dA.

      Mdot_alpha = A^T M_alpha
                   - sum_i alpha_i sum_j A_ij M_{alpha-e_i+e_j}.

    Every required moment on the right has the same total order |alpha|.
    """
    if grad_u.rows != grad_u.cols:
        raise ValueError("grad_u must be square")
    n = grad_u.rows
    _validate_exponent(exponent, n)
    if exponent not in moments:
        raise KeyError(f"missing moment {exponent}")
    M = moments[exponent]
    if M.shape != (n, 1):
        raise ValueError("moment vectors must have spatial dimension")
    out = grad_u.T * M
    for i, power in enumerate(exponent):
        if power == 0:
            continue
        for j in range(n):
            beta = list(exponent)
            beta[i] -= 1
            beta[j] += 1
            beta_t = tuple(beta)
            if beta_t not in moments:
                raise KeyError(f"missing same-order affine moment {beta_t}")
            if moments[beta_t].shape != (n, 1):
                raise ValueError("moment vectors must have spatial dimension")
            out -= power * grad_u[i, j] * moments[beta_t]
    return sp.simplify(out)


def polynomial_vector_total_degree(field: Matrix, coords: Sequence[sp.Symbol]) -> int:
    """Maximum total polynomial degree among nonzero components; -1 for zero field."""
    degrees: list[int] = []
    for q in field:
        q = sp.expand(q)
        if q == 0:
            continue
        degrees.append(sp.Poly(q, *coords).total_degree())
    return max(degrees) if degrees else -1


def homogeneous_moment_rate_degree(
    rate_integrand: Matrix,
    coords: Sequence[sp.Symbol],
) -> set[int]:
    """Total degrees carried by nonzero components of a polynomial rate integrand."""
    degrees: set[int] = set()
    for q in rate_integrand:
        q = sp.expand(q)
        if q == 0:
            continue
        poly = sp.Poly(q, *coords)
        for monom, coeff in poly.terms():
            if coeff != 0:
                degrees.add(sum(monom))
    return degrees


def shifted_exponent(exponent: Exponent, i: int, j: int) -> Exponent:
    """alpha-e_i+e_j, used by the affine same-order connection."""
    beta = list(exponent)
    if beta[i] <= 0:
        raise ValueError("cannot lower a zero exponent")
    beta[i] -= 1
    beta[j] += 1
    return tuple(beta)


def monomial_coefficients_vector(
    field: Matrix,
    coords: Sequence[sp.Symbol],
) -> dict[Exponent, Matrix]:
    """Coefficient vector c_alpha in a polynomial vector field sum c_alpha r^alpha."""
    if field.cols != 1:
        raise ValueError("field must be a column vector")
    nout = field.rows
    coeffs: dict[Exponent, Matrix] = {}
    for component in range(nout):
        poly = sp.Poly(sp.expand(field[component]), *coords)
        for powers, coeff in poly.terms():
            alpha = tuple(int(p) for p in powers)
            if alpha not in coeffs:
                coeffs[alpha] = sp.zeros(nout, 1)
            coeffs[alpha][component] += coeff
    return {alpha: sp.simplify(vec) for alpha, vec in coeffs.items()}


def polynomial_flux_error_from_oriented_moments(
    local_vorticity_profile: Matrix,
    relative_coords: Sequence[sp.Symbol],
    oriented_moments: Mapping[Exponent, Matrix],
) -> sp.Expr:
    """Exact polynomial Stokes descent error from oriented moments at anchor r=0.

      epsilon = sum_{alpha != 0} c_alpha dot M_alpha,

    where omega(r)-omega(0)=sum_{alpha!=0} c_alpha r^alpha.
    """
    coeffs = monomial_coefficients_vector(local_vorticity_profile, relative_coords)
    zero = (0,) * len(relative_coords)
    out = sp.Integer(0)
    for alpha, coeff in coeffs.items():
        if alpha == zero:
            continue
        if alpha not in oriented_moments:
            raise KeyError(f"missing oriented moment {alpha}")
        M = oriented_moments[alpha]
        if M.shape != coeff.shape:
            raise ValueError("moment/vorticity spatial dimension mismatch")
        out += (coeff.T * M)[0]
    return sp.simplify(out)


def polynomial_shape_residual_from_oriented_moments(
    grad_u_profile: Matrix,
    relative_coords: Sequence[sp.Symbol],
    oriented_moments: Mapping[Exponent, Matrix],
) -> Matrix:
    """Exact polynomial R_A=int[A(r)-A(0)]^T n dA from oriented moments."""
    n = len(relative_coords)
    if grad_u_profile.shape != (n, n):
        raise ValueError("grad_u_profile dimension mismatch")
    zero = {x: 0 for x in relative_coords}
    delta = sp.simplify(grad_u_profile - grad_u_profile.subs(zero))
    out = sp.zeros(n, 1)
    for row in range(n):
        for col in range(n):
            poly = sp.Poly(sp.expand(delta[row, col]), *relative_coords)
            for powers, coeff in poly.terms():
                alpha = tuple(int(p) for p in powers)
                if coeff == 0:
                    continue
                if alpha not in oriented_moments:
                    raise KeyError(f"missing oriented moment {alpha}")
                # (A^T M)_col gets A_{row,col} M_row.
                out[col] += coeff * oriented_moments[alpha][row]
    return sp.simplify(out)


def polynomial_error_noise_from_oriented_moments(
    local_vorticity_profile: Matrix,
    relative_coords: Sequence[sp.Symbol],
    oriented_moments: Mapping[Exponent, Matrix],
) -> list[sp.Expr]:
    """Exact polynomial q_mu^err by applying the flux-error contraction to d_mu omega."""
    return [
        polynomial_flux_error_from_oriented_moments(
            sp.diff(local_vorticity_profile, x), relative_coords, oriented_moments
        )
        for x in relative_coords
    ]


def oriented_first_moment_recentering_residual(
    first_moment_matrix: Matrix,
    area_vector: Matrix,
    anchor_shift: Matrix,
) -> Matrix:
    """M1' = M1 - c h^T under r' = r-c.

    Rows of M1 are coordinate moments; columns are oriented-area components.  A
    single anchor shift centers every oriented first moment iff M1=c h^T.
    """
    if area_vector.cols != 1 or anchor_shift.shape != area_vector.shape:
        raise ValueError("area vector and anchor shift must be equal column vectors")
    n = area_vector.rows
    if first_moment_matrix.shape != (n, n):
        raise ValueError("first moment matrix must be n x n")
    return sp.simplify(first_moment_matrix - anchor_shift * area_vector.T)
