from __future__ import annotations

import json
from pathlib import Path
import sys

import sympy as sp

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from pde_audit.active_pair import matrix_is_zero  # noqa: E402
from pde_audit.stochastic_cycle_map import (  # noqa: E402
    ito_cycle_diffusions,
    ito_cycle_drift,
    ito_pair_quadratic_source,
    pair_source_boundary,
    scalar_qv_density,
)


def main() -> None:
    B = sp.Matrix([
        [-1, 0, 1],
        [1, -1, 0],
        [0, 1, -1],
    ])
    K = sp.Matrix([1, 1, 1])
    a, beta, sigma = sp.symbols("a beta sigma")
    J = K * (1 + 2 * a)
    hessians = [sp.Matrix([[2]]) for _ in range(3)]
    drift = ito_cycle_drift(J, sp.Matrix([beta]), hessians, sp.Matrix([[sigma**2]]))
    diffusions = ito_cycle_diffusions(J, sp.Matrix([[sigma]]))
    source = ito_pair_quadratic_source(diffusions)

    aa, tau, nu, k = sp.symbols("a tau nu k", positive=True)
    mean = sp.exp(-nu * k**2 * tau) * sp.cos(k * aa)
    qv = scalar_qv_density(sp.Matrix([sp.diff(mean, aa)]), sp.Matrix([[2 * nu]]))
    gamma = sp.simplify(2 * nu * sp.diff(mean, aa) ** 2)

    report = {
        "classification": {
            "finite_variation_selector": "Exact: no extra observer quadratic variation",
            "stochastic_cycle_map_ito_drift": "Exact cycle-valued Itô formula",
            "stochastic_cycle_pair_source": "Exact martingale quadratic-variation/carre-du-champ source",
            "pair_source_boundary": "Exact zero when diffusion tangents are closed cycles",
            "one_mode_kelvin_qv": "Exact NS/Kelvin calibration of the carre-du-champ channel",
            "global_S_int": "Still undefined; stochastic q.v. is a named physical channel and is not relabelled S^int",
            "continuation_restart": "Open; no regularity conclusion",
        },
        "nonlinear_stochastic_cycle": {
            "ito_drift_boundary_zero": matrix_is_zero(B * drift),
            "diffusion_boundary_zero": all(matrix_is_zero(B * psi) for psi in diffusions),
            "pair_qv_source_nonzero_symbolically": not matrix_is_zero(source),
            "pair_qv_source_boundary_zero": matrix_is_zero(pair_source_boundary(B, source)),
            "pair_qv_source": [str(v) for v in source],
        },
        "finite_variation": {
            "extra_pair_qv_source_zero": matrix_is_zero(ito_pair_quadratic_source([sp.zeros(3, 1)])),
        },
        "one_mode_kelvin": {
            "qv_density": str(sp.factor(qv)),
            "kelvin_gamma": str(sp.factor(gamma)),
            "qv_equals_gamma": sp.simplify(qv - gamma) == 0,
        },
        "frontier": {
            "deterministic_or_finite_variation_cycle_motion": "connection/covariance/reset work; no q.v. source",
            "stochastic_cycle_motion": "explicit pair q.v./carre-du-champ source with future-variance interpretation",
            "cycle_breaking_diffusion": "would be physical boundary/gauge-visible and must be classified separately",
            "untyped_internal_source": "none generated by Itô bookkeeping itself",
            "remaining_literal_datum": "line-by-line S^int or independently intended Z_irr definition",
        },
    }

    out = ROOT / "audit-results" / "stochastic_cycle_map_report.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")
    print(out)
    print("Ito drift boundary zero:", report["nonlinear_stochastic_cycle"]["ito_drift_boundary_zero"])
    print("diffusion boundary zero:", report["nonlinear_stochastic_cycle"]["diffusion_boundary_zero"])
    print("pair qv source nonzero:", report["nonlinear_stochastic_cycle"]["pair_qv_source_nonzero_symbolically"])
    print("pair qv source boundary zero:", report["nonlinear_stochastic_cycle"]["pair_qv_source_boundary_zero"])
    print("finite variation extra qv zero:", report["finite_variation"]["extra_pair_qv_source_zero"])
    print("one-mode qv equals Kelvin gamma:", report["one_mode_kelvin"]["qv_equals_gamma"])


if __name__ == "__main__":
    main()
